version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=school_management
    ports:
      - 3307:3306
    expose:
      - 3306

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_DATABASE=school_management
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    ports:
      - 1507:1507

  nginx:
    image: nginx:1.27.0-alpine
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:80
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:


networks:
  backend:
  frontend:
