version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=school_management
    ports:
      - 3307:3306
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=1507
      - JWT_SECRET_KEY=24educationjwtkey
      - JWT_EXPRIRES_IN=1d
      - REACT_URL=http://localhost:5173
      - DB_PORT=3306
      - DB_HOST=mysqldb
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DATABASE=school_management
    ports:
      - 1507:1507
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    environment:
      - VITE_serverURL=http://server:1507
    command: [ "npm", "run", "start", "--", "--host", "0.0.0.0" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
